// Deterministic stand-in for a PrusaSlicer-compatible CLI, used by contract tests and
// the loopback workspace (SLICER_PROVIDER=local-cli SLICER_BIN=<this file>).
import { readFileSync, writeFileSync } from "node:fs";

const args = process.argv.slice(2);
if (args.includes("--help")) { console.log("FakeSlicer-9.9.9 (test double)"); process.exit(0); }
const mode = (args.find(arg => arg.startsWith("--mode=")) ?? "--mode=ok").slice(7);
const output = args[args.indexOf("--output") + 1];
const model = args.at(-1);
if (mode === "fail") { console.error("simulated failure with private detail"); process.exit(3); }
if (mode === "hang") setTimeout(() => {}, 60_000);
else {
  const size = readFileSync(model).length;
  const grams = Math.round((5 + size / 100) * 100) / 100;
  const summary = mode === "empty" ? "G1 X0 Y0\n" : [
    "; generated by FakeSlicer 9.9.9 on 2026-09-30 at 12:00:00 UTC",
    "G1 X0 Y0",
    `; filament used [mm] = ${Math.round(grams * 330)}`,
    `; filament used [g] = ${grams}`,
    "; total toolchanges = 0",
    "; estimated printing time (normal mode) = 1h 12m 30s",
    "; total layers count = 100",
    ""
  ].join("\n");
  writeFileSync(output, summary);
}
