import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { categorizeReturnCode, createBambuCliSlicer, parseBambuGcodeHeader, parseBambuResult } from "../../lib/print-estimation/adapters/bambu-cli-slicer.js";
import { createSlicerFromEnv } from "../../lib/print-estimation/runtime.js";
import { normalizeSliceResult } from "../../lib/print-estimation/slicer-contract.js";

const fixtures = new URL("../fixtures/print-estimation/", import.meta.url);
const fakeSlicer = fileURLToPath(new URL("fake-bambu-slicer.mjs", fixtures));
const model = async () => new Uint8Array(await readFile(new URL("cube-20mm-binary.stl", fixtures)));
const categoryOf = async promise => { try { await promise; return "resolved"; } catch (error) { assert.equal(error.name, "SliceError"); return error.category; } };

async function withPresets(run) {
  const directory = await mkdtemp(join(tmpdir(), "3dp-bambu-presets-"));
  try {
    const write = async (name, body) => { const path = join(directory, name); await writeFile(path, JSON.stringify(body)); return path; };
    const paths = {
      process: await write("process.json", { type: "process", name: "0.16mm High Quality @BBL X2D" }),
      pla: await write("filament-pla.json", { type: "filament", name: "Generic PLA @BBL X2D 0.4 nozzle" }),
      petg: await write("filament-petg.json", { type: "filament", name: "Generic PETG @BBL X2D 0.4 nozzle", fake_grams: 4.2 }),
      tpu: await write("filament-tpu.json", { type: "filament", name: "Generic TPU @BBL X2D 0.4 nozzle", fake_needs_bed: true })
    };
    const machine = async mode => write(`machine-${mode}.json`, { type: "machine", name: "Bambu Lab X2D 0.4 nozzle", fake_mode: mode });
    const slicer = async (mode = "ok", extra = {}) => createBambuCliSlicer({
      bin: fakeSlicer, machinePath: await machine(mode), processPath: paths.process, filamentPaths: { pla: paths.pla, petg: paths.petg },
      profileId: "x2d-0.16hq-v1", ...extra
    });
    await run({ slicer, paths, machine });
  } finally { await rm(directory, { recursive: true, force: true }); }
}

test("captured Bambu Studio output parses to time, grams, layers, and version", async () => {
  const header = parseBambuGcodeHeader(await readFile(new URL("bambu-plate-header.gcode", fixtures), "utf8"));
  assert.deepEqual(header, { elapsedSeconds: 1447, materialGrams: 3.57, materialMm: 1196.07, layerCount: 125, version: "BambuStudio 02.08.04.57" });
  const result = parseBambuResult(await readFile(new URL("bambu-result.json", fixtures), "utf8"));
  assert.equal(result.returnCode, 0);
  assert.equal(result.plateCount, 1);
  assert.ok(Math.abs(result.elapsedSeconds - 1447.55) < 0.01);
  assert.ok(Math.abs(result.materialGrams - 3.567) < 0.001);
  assert.equal(parseBambuResult("not json"), null);
  assert.equal(parseBambuGcodeHeader("; generated by OrcaSlicer 2.4.2 on 2026-10-01\n; total estimated time: 1h 2m 3s\n").elapsedSeconds, 3723);
});

test("Bambu CLI adapter returns a normalized estimate and maps the material to its filament preset", async () => {
  await withPresets(async ({ slicer }) => {
    const pla = normalizeSliceResult(await (await slicer()).estimateSlice({ bytes: await model(), filename: "cube.stl", options: { material: "pla" } }));
    assert.deepEqual(
      { engine: pla.engine, version: pla.engineVersion, profile: pla.profileId, seconds: pla.elapsedSeconds, grams: pla.materialGrams, layers: pla.layerCount, tools: pla.toolChanges },
      { engine: "bambu-studio-cli", version: "02.08.04.57", profile: "x2d-0.16hq-v1:pla", seconds: 1447.55, grams: 3.57, layers: 125, tools: 0 }
    );
    const petg = await (await slicer()).estimateSlice({ bytes: await model(), filename: "cube.3mf", options: { material: "petg" } });
    assert.equal(petg.materialGrams, 4.2);
    assert.equal(petg.profileId, "x2d-0.16hq-v1:petg");
    const other = await (await slicer()).estimateSlice({ bytes: await model(), filename: "cube.stl", options: { material: "other" } });
    assert.equal(other.profileId, "x2d-0.16hq-v1", "unmapped materials fall back to the default filament without a suffix");
    const orca = await (await slicer("header-only", { engine: "orca-slicer-cli" })).estimateSlice({ bytes: await model(), filename: "cube.stl" });
    assert.deepEqual({ engine: orca.engine, version: orca.engineVersion, seconds: orca.elapsedSeconds, grams: orca.materialGrams }, { engine: "orca-slicer-cli", version: "2.4.2", seconds: 1447, grams: 3.57 });
  });
});

test("Bambu CLI failures map to bounded categories without raw output", async () => {
  await withPresets(async ({ slicer }) => {
    const bytes = await model();
    assert.equal(await categoryOf((await slicer("reject")).estimateSlice({ bytes, filename: "cube.stl" })), "unsupported");
    assert.equal(await categoryOf((await slicer("config")).estimateSlice({ bytes, filename: "cube.stl" })), "unavailable");
    assert.equal(await categoryOf((await slicer("crash")).estimateSlice({ bytes, filename: "cube.stl" })), "slicer_failed");
    assert.equal(await categoryOf((await slicer("empty")).estimateSlice({ bytes, filename: "cube.stl" })), "invalid_output");
    assert.equal(await categoryOf((await slicer("hang")).estimateSlice({ bytes, filename: "cube.stl", timeoutMs: 400 })), "timeout");
    try { await (await slicer("crash")).estimateSlice({ bytes, filename: "cube.stl" }); }
    catch (error) { assert.doesNotMatch(error.message, /private detail/); }
  });
  assert.equal(categorizeReturnCode(-6), "unsupported");
  assert.equal(categorizeReturnCode(-14), "slicer_failed");
  assert.throws(() => createBambuCliSlicer({ bin: "x", machinePath: "m.json" }), TypeError);
});

test("SLICER_PROVIDER=bambu-cli is wired from the environment", async () => {
  await withPresets(async ({ paths, machine }) => {
    const slicer = createSlicerFromEnv({ env: {
      SLICER_PROVIDER: "bambu-cli", SLICER_BIN: fakeSlicer, SLICER_MACHINE_PROFILE: await machine("ok"), SLICER_PROCESS_PROFILE: paths.process,
      SLICER_FILAMENT_PROFILES: `pla=${paths.pla};petg=${paths.petg}`, SLICER_PROFILE_ID: "env-profile"
    } });
    assert.equal(slicer.engine, "bambu-studio-cli");
    const result = await slicer.estimateSlice({ bytes: await model(), filename: "cube.stl", options: { material: "petg" } });
    assert.equal(result.profileId, "env-profile:petg");
    assert.equal(result.materialGrams, 4.2);

    // Filaments are validated against the build plate; without SLICER_BED_TYPE the CLI rejects them (-61).
    const base = { SLICER_PROVIDER: "bambu-cli", SLICER_BIN: fakeSlicer, SLICER_MACHINE_PROFILE: await machine("ok"), SLICER_PROCESS_PROFILE: paths.process, SLICER_FILAMENT_PROFILES: `tpu=${paths.tpu}` };
    const tpu = { bytes: await model(), filename: "cube.stl", options: { material: "tpu" } };
    assert.equal(await categoryOf(createSlicerFromEnv({ env: base }).estimateSlice(tpu)), "unavailable");
    assert.equal((await createSlicerFromEnv({ env: { ...base, SLICER_BED_TYPE: "Textured PEI Plate" } }).estimateSlice(tpu)).profileId, "machine-ok.json+process.json:tpu");
  });
});
