import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { createHttpSlicer } from "../../lib/print-estimation/adapters/http-slicer.js";
import { createLocalCliSlicer, parseDuration, parseGcodeSummary } from "../../lib/print-estimation/adapters/local-cli-slicer.js";
import { createLocalPrintRepository } from "../../lib/print-estimation/adapters/local-print-repository.js";
import { createEstimateSessionUseCases } from "../../lib/print-estimation/application/estimate-session.js";
import { createFilamentUseCases } from "../../lib/print-estimation/application/filament.js";
import { createSliceJobRunner, retryDelaySeconds } from "../../lib/print-estimation/application/slice-jobs.js";
import { resolveModelLimits } from "../../public/assets/js/print-estimation/mesh.js";
import { normalizeSliceResult, SliceError } from "../../lib/print-estimation/slicer-contract.js";

const fakeSlicer = fileURLToPath(new URL("../fixtures/print-estimation/fake-slicer.mjs", import.meta.url));
const model = async () => new Uint8Array(await readFile(new URL("../fixtures/print-estimation/cube-20mm-binary.stl", import.meta.url)));
const cli = (mode = "ok", extra = {}) => createLocalCliSlicer({ bin: fakeSlicer, args: ["--export-gcode", `--mode=${mode}`, "--output", "{output}", "{model}"], profileId: "pla-0.20mm-standard", ...extra });
const categoryOf = async promise => { try { await promise; return "resolved"; } catch (error) { assert.equal(error.name, "SliceError"); return error.category; } };

test("local CLI slicer returns engine, version, profile, time, and material deterministically", async () => {
  const result = normalizeSliceResult(await cli().estimateSlice({ bytes: await model(), filename: "cube.stl" }));
  assert.deepEqual({ engine: result.engine, engineVersion: result.engineVersion, profileId: result.profileId }, { engine: "prusaslicer-cli", engineVersion: "9.9.9", profileId: "pla-0.20mm-standard" });
  assert.equal(result.elapsedSeconds, 4350);
  assert.equal(result.materialGrams, 11.84);
  assert.equal(result.layerCount, 100);
  assert.equal(result.toolChanges, 0);
});

test("local CLI slicer failures map to bounded categories without raw output", async () => {
  assert.equal(await categoryOf(cli("fail").estimateSlice({ bytes: await model(), filename: "cube.stl" })), "slicer_failed");
  assert.equal(await categoryOf(cli("hang").estimateSlice({ bytes: await model(), filename: "cube.stl", timeoutMs: 400 })), "timeout");
  const empty = await cli("empty").estimateSlice({ bytes: await model(), filename: "cube.stl" });
  assert.throws(() => normalizeSliceResult(empty), error => error.category === "invalid_output");
  assert.equal(await categoryOf(createLocalCliSlicer({ bin: join(tmpdir(), "missing-slicer-binary") }).estimateSlice({ bytes: await model(), filename: "cube.stl" })), "unavailable");
  try { await cli("fail").estimateSlice({ bytes: await model(), filename: "cube.stl" }); }
  catch (error) { assert.doesNotMatch(error.message, /private detail/); }
});

test("G-code summary parsing supports common slicer comment formats", () => {
  assert.equal(parseDuration("1d 2h 3m 4s"), 93784);
  assert.equal(parseDuration("45m"), 2700);
  assert.equal(parseDuration("soon"), null);
  const summary = parseGcodeSummary("; generated by PrusaSlicer 2.8.1+win64 on 2026\n; filament used [g] = 10.5, 2.5\n; filament used [mm] = 100, 20\n; total toolchanges = 12\n; estimated printing time (normal mode) = 2h 0m 0s\n");
  assert.deepEqual({ grams: summary.materialGrams, mm: summary.materialMm, tools: summary.toolChanges, seconds: summary.elapsedSeconds, version: summary.version }, { grams: 13, mm: 120, tools: 12, seconds: 7200, version: "PrusaSlicer 2.8.1+win64" });
});

test("the HTTP provider sends a short-lived signed model URL, never bytes, and maps failures", async () => {
  const requests = [];
  const slicer = createHttpSlicer({
    url: "https://slicer.example/estimate", token: "t".repeat(40), signDownload: async (path, seconds) => `https://blob.example/${path}?ttl=${seconds}`,
    fetchImpl: async (url, init) => { requests.push({ url, init }); return new Response(JSON.stringify({ engine: "orca", engineVersion: "2.1", profileId: "p", elapsedSeconds: 60, materialGrams: 3 }), { status: 200 }); }
  });
  assert.equal(slicer.needsBytes, false);
  const result = normalizeSliceResult(await slicer.estimateSlice({ blobPath: "print-estimates/est_x/a-cube.stl", filename: "cube.stl", options: { material: "pla" } }));
  assert.equal(result.engine, "orca");
  const body = JSON.parse(requests[0].init.body);
  assert.equal(body.modelUrl, "https://blob.example/print-estimates/est_x/a-cube.stl?ttl=600");
  assert.equal("bytes" in body, false);
  assert.equal(requests[0].init.headers.Authorization, `Bearer ${"t".repeat(40)}`);
  for (const [status, category] of [[422, "unsupported"], [500, "unavailable"], [400, "slicer_failed"]]) {
    const failing = createHttpSlicer({ url: "https://slicer.example", token: "t".repeat(40), signDownload: async () => "u", fetchImpl: async () => new Response("{}", { status }) });
    assert.equal(await categoryOf(failing.estimateSlice({ blobPath: "x", filename: "a.stl", options: {} })), category);
  }
  assert.throws(() => createHttpSlicer({ url: "http://insecure", token: "t".repeat(40) }), TypeError);
});

test("the job runner records an immutable slicer estimate and retries with bounded backoff", { timeout: 30_000 }, async () => {
  const directory = await mkdtemp(join(tmpdir(), "3dp-slice-runner-"));
  try {
    const repository = createLocalPrintRepository({ path: join(directory, "print.json") });
    const objects = new Map();
    const fileStore = { async authorizeUpload() { return { uploadUrl: "u" }; }, async inspect(path) { return objects.has(path) ? { size: objects.get(path).length } : null; }, async read(path) { return objects.get(path); }, async delete(path) { objects.delete(path); } };
    const materialCosts = createFilamentUseCases({ repository });
    const estimates = createEstimateSessionUseCases({ repository, fileStore, materialCosts, slicerEnabled: true });
    const session = await estimates.create({ options: { material: "pla", quantity: 3 } });
    const upload = await estimates.authorizeUpload({ ...session, filename: "cube.stl", size: 684 });
    objects.set((await repository.findAsset(upload.assetId)).blobPath, await model());
    const geometry = await estimates.analyze({ ...session, assetId: upload.assetId, options: { material: "pla", quantity: 3 } });
    assert.equal(geometry.slice.status, "pending");

    let clock = new Date();
    let attempts = 0;
    const flaky = { async estimateSlice(input) { attempts += 1; if (attempts === 1) throw new SliceError("timeout", "slow"); return cli().estimateSlice(input); } };
    const runner = createSliceJobRunner({ repository, fileStore, slicer: flaky, materialCosts, limits: resolveModelLimits(), now: () => clock });
    assert.deepEqual(await runner.runOnce(), { claimed: 1, ready: 0, retrying: 1, failed: 0 });
    assert.deepEqual(await runner.runOnce(), { claimed: 0, ready: 0, retrying: 0, failed: 0 }, "backoff delays the retry");
    const [pendingJob] = await repository.listAssetJobs(upload.assetId);
    assert.equal(pendingJob.lastErrorCategory, "timeout");
    const snapshot = await repository.snapshot();
    snapshot.jobs[0].nextAttemptAt = new Date(0).toISOString();
    const { writeFile } = await import("node:fs/promises");
    await writeFile(repository.path, JSON.stringify(snapshot));
    assert.deepEqual(await runner.runOnce(), { claimed: 1, ready: 1, retrying: 0, failed: 0 });

    const status = await estimates.status(session);
    assert.equal(status.slice.status, "ready");
    assert.equal(status.slice.confidence, "better");
    assert.equal(status.slice.production.estimatedGramsPerUnit, 11.8);
    const [slice] = (await repository.listSessionEstimates(session.sessionId, 5)).filter(row => row.estimatorType === "slicer");
    assert.deepEqual({ engine: slice.engine, version: slice.engineVersion, profile: slice.profileId, purpose: slice.purpose }, { engine: "prusaslicer-cli", version: "9.9.9", profile: "pla-0.20mm-standard", purpose: "slice" });
    assert.equal(slice.slicer.elapsedSeconds, 4350);
    assert.equal(slice.cost.totalGrams, 11.84 * 3);
    assert.ok(slice.pricing.spread < geometry.price.high / geometry.price.low, "slicer band is narrower");

    const permanent = createSliceJobRunner({ repository, fileStore, slicer: { async estimateSlice() { throw new SliceError("unsupported", "no"); } }, materialCosts, limits: resolveModelLimits() });
    await estimates.analyze({ ...session, assetId: upload.assetId, options: { material: "petg", quantity: 3 } });
    assert.deepEqual(await permanent.runOnce(), { claimed: 1, ready: 0, retrying: 0, failed: 1 }, "permanent failures are not retried");
    assert.equal(retryDelaySeconds(1), 60);
    assert.equal(retryDelaySeconds(20), 3600);
  } finally { await rm(directory, { recursive: true, force: true }); }
});
